### ISSUE TITLE
Add excludeSelf option for Child and Parent attributes

### ISSUE THREAD

**Issue by Niikelion** [KyleBanks/scene-ref-attribute#19]
It would be really helpfull if we could specify that we don't wont to include current gameobject in the component search. This way we can for example get reference to the  `Transform` of child/parent using `Child` / `Parent`

**Comment by KyleBanks** [comment]
Great idea 👍
I'll see if I can include this in a future update, or feel free to submit a PR if you're up for it

**Comment by Niikelion** [comment]
Started working on it. I'll make PR later today/tomorrow.
