### ISSUE TITLE
unity conditional compilation problem

### ISSUE THREAD

**Issue by MikailY** [KyleBanks/scene-ref-attribute#23]
Hey, 

I am using unity version 2021.3.11f and wanted to use the latest version (0.9.0) for this tool. But I am getting and error on SceneRefAttributeValidator.cs at line 300, it cannot resolve "FindObjectsInactive".

![image_2023-10-12_113219376](https://github.com/KyleBanks/scene-ref-attribute/assets/32931973/6da61664-d426-4b3b-b5d8-a95d9847757c)

Maybe the problem is with the conditional parameter (UNITY_2020_OR_NEWER) because for my unity version the else part of the code should not be compiled. I am just going to remove this part out for now but just wanted to give you a heads up. 

Also thanks for sharing this great tool.

**Comment by KyleBanks** [comment]
Thanks for raising @MikailY, this is resolved in v0.9.1
