### ISSUE TITLE
Add a way to check whether there are any validation errors when building

### ISSUE THREAD

**Issue by duckblaster** [KyleBanks/scene-ref-attribute#24]
I would like to be able to enforce validation when building and stop the build if there are any errors.
Perhaps changing `SceneRefAttributeValidator.ValidateAllRefs` to be `public static bool` instead of `private static void` would be a start?
Would mean changing all validation calls from `void` to `bool`, but I am happy to submit a pull request if you would like.

**Comment by KyleBanks** [comment]
Hey @duckblaster, that sounds like a reasonable improvement to me, feel free to submit a PR and I can merge that in
