### ISSUE TITLE
Attribute Scene doesn't work with interface refs

### ISSUE THREAD

**Issue by DavidNightinga1e** [KyleBanks/scene-ref-attribute#27]
`[SerializeField, Scene] private InterfaceRef<IExampleInterface> instance;`

Throws exception
`FindAllObjectsOfType: The type has to be derived from UnityEngine.Object. Type is IExampleInterface.`

**Comment by DavidNightinga1e** [comment]
If this is by design, I suggest adding custom exception/error log

**Comment by KyleBanks** [comment]
That would be lovely, thanks @Niikelion
