### ISSUE TITLE
[Scene] attribute keeps reordering serialized field in collection, hence creating git changes noise

### ISSUE THREAD

**Issue by Benoit-Prigent** [KyleBanks/scene-ref-attribute#29]
Hello,

I'm using the `[Scene]` attribute to references "IService" interface in my game scene, and I noticed that whenever I open the scene, the serialized reference set by the attribute reorganize themselves. Which is annoying since it is detected as modification by Git.
The same thing happens for other `[Scene]` attributes on collection, not only interface references.

Maybe the package could use the [sort mode](https://docs.unity3d.com/ScriptReference/FindObjectsSortMode.html) : "InstanceId" by default when using the "FindObjectsByType" function ?

Unity Version : 2022.3.4f1
Package version : 0.11.1

![image](https://github.com/KyleBanks/scene-ref-attribute/assets/66417910/6322b773-53d2-4317-8729-10bcfa7777e7)
![image](https://github.com/KyleBanks/scene-ref-attribute/assets/66417910/fe16cf3f-0b26-4ea4-b093-40381b82889a)

**Comment by KyleBanks** [comment]
Ah interesting, yeah that's definitely a nuisance. Using the sort mode sounds like a good idea, feel free to submit a PR if you're up for it or I can take a look when I get some time.

**Comment by Niikelion** [comment]
Good idea! This seems like a quick fix so I can try to find some time for it on the weekend.
