### ISSUE TITLE
0.12.2 does not install with UPM

### ISSUE THREAD

**Issue by pjarnfelt** [KyleBanks/scene-ref-attribute#34]
Latest version that installs is 0.12.1
<img width="841" alt="Screenshot 2024-09-17 at 13 50 06" src="https://github.com/user-attachments/assets/15235998-4a65-46b3-a190-c02ee2458c6a">

**Comment by andreiagmu** [comment]
One workaround is to install using the Git URL.

Add this line to your `Packages\manifest.json` file:
`"com.kylewbanks.scenerefattribute": "https://github.com/KyleBanks/scene-ref-attribute.git",`

This will install the latest commit from the `main` branch, including the `v0.12.2` stuff.

**Comment by KyleBanks** [comment]
Should be fixed with v0.13.0
